@host=localhost:8080
@v1=/api/v1

###

GET {{v1}}/health
Host: {{host}}

###

# @name login
POST {{v1}}/login
Host: {{host}}

{
  "target": "admin",
  "password": "admin"
}


###

@token = {{login.response.body.data.access_token}}

###

GET {{v1}}/self
Host: {{host}}
Authorization: Bearer {{token}}
